version: 2
jobs:
  build:
    working_directory: ~/me-ventures/microservice-toolkit
    parallelism: 1
    shell: /bin/bash --login

    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
      - checkout
      - run:
            working_directory: ~/me-ventures/microservice-toolkit
            command: nvm install 10 && nvm alias default 10
      - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
      - run: export PATH="~/me-ventures/microservice-toolkit/node_modules/.bin:$PATH"
      - run:
          name: build site
          command: yarn install
      - run:
          name: test site
          command: yarn run test
