version: 2
jobs:
  build:
    docker:
      - image: meventures/angular-cli:3.1.0
    working_directory: /app
    parallelism: 1
    environment:
    steps:
      - run:
          name: build site
          command: yarn install && yarn run build
      - run:
          name: run tests
          command: yarn run test
